POST http://localhost:3000/item
Content-Type: application/json

{
        "name": "chipsw",
        "quantity": 2
}

###

GET http://localhost:3000/items

###

PUT  http://localhost:3000/item/6222484f2493ee9328a82e69/quantity/3